_welcome:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo
    
_post:
    resource: "@AcmeDemoBundle/Controller/PostController.php"
    type: annotation 
    prefix:   /demo   

_rest_post:
    resource: Acme\DemoBundle\Controller\RestPostController
    type:     rest
    prefix:   /demo_rest
