Acme\DemoBundle\Entity\Post:
    properties:
        title:
            - NotBlank: ~
            - Length:
                min: 3
                max: 50
                minMessage: "Your title must be at least {{ limit }} characters length"
                maxMessage: "Your title cannot be longer than {{ limit }} characters length"
        body:
            - NotBlank: ~
            - Length:
                min: 10
                max: 50
                minMessage: "Your body  must be at least {{ limit }} characters length"
                maxMessage: "Your body  cannot be longer than {{ limit }} characters length"